# -----------------------------------------------------------------------------#
name: Environments
# -----------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/env.yaml'
      - 'env/*.yaml'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
# -----------------------------------------------------------------------------#
jobs:
# -----------------------------------------------------------------------------#
  # Check the conda environment
  conda:
    runs-on: ubuntu-latest
    steps:
      #------------------------------------------------------------------------#
      # Env setup
      - name: setup environment variables
        run: |
          echo "CONDA_ENVS_PATH=/home/runner/miniconda/envs:/usr/share/miniconda/envs" >> $GITHUB_ENV
          echo "CONDA_PKGS_DIRS=/home/runner/miniconda/pkgs" >> $GITHUB_ENV
      #------------------------------------------------------------------------#
      # Checkout repo
      - uses: actions/checkout@v2
      #------------------------------------------------------------------------#
      # Setup conda with mamba
      - name: setup conda
        uses: goanpeca/setup-miniconda@v2
        with:
          auto-update-conda: true
          # mamba-version: "*"
          # channels: conda-forge
      # Install environment
      - name: create conda env
        run: conda env create -f env/conda.yaml
